Tokenización
La tokenización es un paso crucial en las tareas de PLN (Procesamiento del Lenguaje Natural), donde el texto se divide en unidades más pequeñas llamadas tokens. Estos tokens pueden variar desde caracteres individuales hasta oraciones completas, aunque suelen ser palabras o subpalabras.

Lemantización
En el campo del procesamiento del lenguaje natural (PLN), la lematización es el proceso de reducir las palabras a su forma base, conocida como lema. Esto ayuda a agrupar palabras similares considerando su significado y estructura gramatical. De esta manera, se garantiza que las palabras con significados similares reciban el mismo tratamiento.

Referencias

Educative. (2026). *Diferencia entre tokenización y lematización en PLN*. Educative. https://www-educative-io.translate.goog/answers/difference-between-tokenization-and-lemmatization-in-nlp?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=tc&_x_tr_hist=true

In [1]:
!pip install -U scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 60.3 MB/s eta 0:00:00
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
Successfully installed scikit-learn-1.8.0

In [2]:
import pandas as pd

In [29]:
#Spanish News Classification data set
df = pd.read_csv ('/content/clinical_notes_full.csv')

In [30]:
df

,id,task_type,specialty,language,instruction,input,output
0,1,patient_education,Gastroenterology,English,You are a clinical communication AI. Rewrite t...,Patient diagnosed with GERD. Initiated on pant...,You have been diagnosed with GERD. We are star...
1,2,icd10_coding,Nephrology,English,You are a medical coding AI. Assign the correc...,Discharge Diagnosis: Contrast-induced nephropa...,Primary ICD-10-CM Code: Z99.9\nDescription: Ot...
2,3,icd10_coding,Nephrology,English,You are a medical coding AI. Assign the correc...,Discharge Diagnosis: Acute kidney injury\nPati...,Primary ICD-10-CM Code: N17.9\nDescription: Ac...
3,4,patient_education,Emergency Medicine,English,You are a clinical communication AI. Rewrite t...,Patient diagnosed with Septic shock. Initiated...,You have been diagnosed with Septic shock. We ...
4,5,clinical_qa,Oncology,English,You are a clinical AI assistant providing evid...,How is the Glasgow Coma Scale scored?,GCS components: Eye opening (E): Spontaneous=4...
...,...,...,...,...,...,...,...
14995,14996,radiology_impression,Oncology,English,You are a radiology AI assistant. Given the fo...,Chest X-ray findings: Consolidation of the rig...,IMPRESSION: Right lower lobe consolidation con...
14996,14997,clinical_risk_scoring,Psychiatry,English,You are a clinical decision support AI. Calcul...,"A 72-year-old female with atrial fibrillation,...","Score: 4 (Age ≥75: 0, Age 65-74: 1, Female: 1,..."
14997,14998,clinical_risk_scoring,Nephrology,English,You are a clinical decision support AI. Calcul...,55-year-old male smoker with crushing chest pa...,"Score: 7 (History highly suspicious: 2, ECG LB..."
14998,14999,differential_diagnosis,Endocrinology,English,You are a clinical reasoning AI. Generate a pr...,51-year-old male presenting with polyuria and ...,Differential Diagnosis for polyuria and polydi...
14999,15000,clinical_risk_scoring,Pulmonology,English,You are a clinical decision support AI. Calcul...,65-year-old male with community-acquired pneum...,"Score: 4 (Confusion: 1, BUN >19: 1, RR ≥30: 1,..."

In [31]:
df.output[3]

'You have been diagnosed with Septic shock. We are starting treatment with heparin. Take your medication every day as prescribed. Write down any new or worsening symptoms. Come back for your follow-up appointment — this is important for your recovery.'

In [32]:
X = df['output']
y = df['specialty']

In [34]:
print(df['specialty'].value_counts())

specialty
Gastroenterology      1500
Nephrology            1500
Emergency Medicine    1500
Oncology              1500
Cardiology            1500
Internal Medicine     1500
Endocrinology         1500
Pulmonology           1500
Psychiatry            1500
Neurology             1500
Name: count, dtype: int64

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [46]:
X_train

2147     Absolute indications (AEIOU mnemonic): Acidosi...
10941    Empirical antifungal therapy is indicated in f...
13776    Score: 4 (Active cancer: 1, Post-surgical immo...
12439    Absolute indications (AEIOU mnemonic): Acidosi...
14643    DISCHARGE SUMMARY\n\nAdmitting Diagnosis: Mela...
                               ...
2071     Differential Diagnosis for productive cough:\n...
8579     Score: 4 (Age ≥75: 0, Age 65-74: 1, Female: 1,...
13754    Differential Diagnosis for exertional dyspnea:...
11384    IMPRESSION: Acute left MCA territory ischemic ...
10856    IMPRESSION: Acute appendicitis. Findings are c...
Name: output, Length: 10500, dtype: object

In [47]:
X_test

5749     Differential Diagnosis for wheezing:\n\nPriori...
1500     Score: 7 (History highly suspicious: 2, ECG LB...
8802     DISCHARGE SUMMARY\n\nAdmitting Diagnosis: Type...
12465    Primary ICD-10-CM Code: E11.10\nDescription: T...
3931     IMPRESSION: Acute right-sided subdural hematom...
                               ...
5156     Primary ICD-10-CM Code: K85.9\nDescription: Ac...
11922    Score: 4 (Age ≥75: 0, Age 65-74: 1, Female: 1,...
12075    DISCHARGE SUMMARY\n\nAdmitting Diagnosis: PTSD...
5656     Differential Diagnosis for productive cough:\n...
12472    Score: 4 (Age ≥75: 0, Age 65-74: 1, Female: 1,...
Name: output, Length: 4500, dtype: object

In [48]:
from sklearn.feature_extraction.text import CountVectorizer

In [49]:
vectorizer = CountVectorizer()

In [50]:
X_train_transformed = vectorizer.fit_transform(X_train)
X_test_transformed = vectorizer.transform(X_test)

In [51]:
X_train_transformed

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 363169 stored elements and shape (10500, 1191)>

In [52]:
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

In [53]:
model = MultinomialNB()
model.fit(X_train_transformed, y_train)
y_pred = model.predict(X_test_transformed)

In [54]:
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.5542222222222222

**Lematización**

La lematización es un proceso lingüístico y computacional que reduce las palabras flexionadas (plurales, conjugaciones, etc.) a su forma base o "lema" (la palabra que aparece en el diccionario) utilizando análisis morfológico y contextos. Es esencial en el procesamiento del lenguaje natural (PLN) para normalizar texto.

In [57]:
import spacy

In [59]:
import spacy.cli
spacy.cli.download("en_core_web_sm")

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [60]:
nlp = spacy.load("en_core_web_sm")

In [61]:
def lemmantize_text (text):
  doc = nlp(text)
  return ' '.join([token.lemma_ for token in doc])

In [62]:
df['output_lemmatized'] = df['output'].apply(lemmantize_text)
df['output_lemmatized']

0        you have be diagnose with GERD . we be start t...
1        primary ICD-10 - CM Code : Z99.9 \n descriptio...
2        primary ICD-10 - CM Code : n17.9 \n Descriptio...
3        you have be diagnose with septic shock . we be...
4        GCS component : eye opening ( E ): spontaneous...
                               ...
14995    impression : right low lobe consolidation cons...
14996    score : 4 ( age ≥75 : 0 , Age 65 - 74 : 1 , fe...
14997    score : 7 ( history highly suspicious : 2 , EC...
14998    Differential Diagnosis for polyuria and polydi...
14999    score : 4 ( confusion : 1 , BUN > 19 : 1 , RR ...
Name: output_lemmatized, Length: 15000, dtype: object

In [63]:
df['output_lemmatized'][3]

'you have be diagnose with septic shock . we be start treatment with heparin . take your medication every day as prescribe . write down any new or worsen symptom . come back for your follow - up appointment — this be important for your recovery .'

In [64]:
X = df['output_lemmatized']
y = df['specialty']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
vectorizer = CountVectorizer()
X_train_transformed = vectorizer.fit_transform(X_train)
X_test_transformed = vectorizer.transform(X_test)
model = MultinomialNB()
model.fit(X_train_transformed, y_train)
y_pred = model.predict(X_test_transformed)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.5563333333333333

In [65]:
X_train_transformed

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 410963 stored elements and shape (12000, 1150)>